CREATE DATABASE IF NOT EXISTS games_db;

USE games_db;

CREATE TABLE games(
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    description VARCHAR(250) NOT NULL,
    image VARCHAR(200) NOT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DESCRIBE games;